HclNextGenSocialGoal/ViewModels/HomeViewModel.cs
using System.Collections.Generic;

namespace HclNextGenSocialGoal.Web.ViewModels
{
    public class HomeViewModel
    {

        public IEnumerable<NotificationsViewModel> Notification { get; set; }
        public int? Count { get; set; }

    }
}

HclNextGenSocialGoal/ViewModels/NotificationViewModel.cs
using System;
using HclNextGenSocialGoal.Model.Models;

namespace HclNextGenSocialGoal.Web.ViewModels
{
    public class NotificationViewModel
    {
        public int GroupInvitationId { get; set; }

        public int SupportInvitationId { get; set; }

        public string FromUserId { get; set; }

        public int GroupId { get; set; }

        public string ToUserId { get; set; }

        public DateTime SentDate { get; set; }

        public ApplicationUser FromUser { get; set; }

        public ApplicationUser ToUser { get; set; }

        public virtual Group Group { get; set; }

        public bool Accepted { get; set; }

        public int GoalId { get; set; }

        public virtual Goal Goal { get; set; }
    }
}

HclNextGenSocialGoal/Controllers/GoalController.cs
using AutoMapper;
using HclNextGenSocialGoal.Model.Models;
using HclNextGenSocialGoal.Service;
using HclNextGenSocialGoal.Web.Core.Models;
using HclNextGenSocialGoal.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HclNextGenSocialGoal.Web.Core.Extensions;
using HclNextGenSocialGoal.Web.Mailers;
using HclNextGenSocialGoal.Properties;
using Microsoft.AspNet.Identity;

namespace HclNextGenSocialGoal.Web.Controllers
{
    [Authorize]
    public class GoalController : Controller
    {
        private readonly IGoalService goalService;
        private readonly IMetricService metricService;
        private readonly IFocusService focusService;
        private readonly ISupportService supportService;
        private readonly IUpdateService updateService;
        private readonly ICommentService commentService;
        private readonly IUserService userService;
        public readonly ISecurityTokenService securityTokenService;
        public readonly ISupportInvitationService supportInvitationService;
        private readonly IGoalStatusService goalStatusService;
        private readonly ICommentUserService commentUserService;
        private readonly IUpdateSupportService updateSupportService;

        private IUserMailer userMailer = new UserMailer();
        public IUserMailer UserMailer
        {
            get { return userMailer; }
            set { userMailer = value; }
        }

        public GoalController(IGoalService goalService, IMetricService metricService, IFocusService focusService, ISupportService supportService, IUpdateService updateService, ICommentService commentService, IUserService userService, ISecurityTokenService securityTokenService, ISupportInvitationService supportInvitationService, IGoalStatusService goalStatusService, ICommentUserService commentUserService, IUpdateSupportService updateSupportService)
        {
            this.goalService = goalService;
            this.supportInvitationService = supportInvitationService;
            this.metricService = metricService;
            this.focusService = focusService;
            this.supportService = supportService;
            this.updateService = updateService;
            this.commentService = commentService;
            this.userService = userService;
            this.securityTokenService = securityTokenService;
            this.goalStatusService = goalStatusService;
            this.commentUserService = commentUserService;
            this.updateSupportService = updateSupportService;
        }

        public ActionResult Index(int id)
        {
            var goal = goalService.GetGoal(id);
            if (goal == null)
            {
                return HttpNotFound();
            }
            var goalDetails = Mapper.Map<Goal, GoalViewModel>(goal);
            goalDetails.Supported = supportService.IsGoalSupported(id, User.Identity.GetUserId());
            var goalstatus = goalStatusService.GetGoalStatus();
            goalDetails.GoalStatuses = goalstatus.ToSelectListItems(goal.GoalStatusId);
            return View(goalDetails);
        }

        public ViewResult MyGoal()
        {
            string userid = User.Identity.GetUserId();
            var Goals = goalService.GetMyGoals(userid);
            var goalDetails = Mapper.Map<IEnumerable<Goal>, IEnumerable<GoalViewModel>>(Goals);
            return View(goalDetails);
        }

        public ViewResult FollowedGoal()
        {
            var followed = supportService.GetUserSupportedGoals(User.Identity.GetUserId(), goalService);
            return View(followed);
        }

        public PartialViewResult Create()
        {
            var createGoal = new GoalFormModel();
            var metrics = metricService.GetMetrics();
            var goalstatus = goalStatusService.GetGoalStatus();
            createGoal.Metrics = metrics.ToSelectListItems(-1);
            return PartialView(createGoal);
        }

        [HttpPost]
        public ActionResult Create(GoalFormModel createGoal)
        {
            Goal goal = Mapper.Map<GoalFormModel, Goal>(createGoal);
            var errors = goalService.CanAddGoal(goal, updateService).ToList();
            ModelState.AddModelErrors(errors);
            if (ModelState.IsValid)
            {
                goalService.CreateGoal(goal);
                return RedirectToAction("Index", new { id = goal.GoalId });
            }
            var metrics = metricService.GetMetrics();
            var goalstatuss = goalStatusService.GetGoalStatus();
            createGoal.Metrics = metrics.ToSelectListItems(-1);
            return View("Create", createGoal);
        }

        public ActionResult Edit(int id)
        {
            var goal = goalService.GetGoal(id);
            GoalFormModel editGoal = Mapper.Map<Goal, GoalFormModel>(goal);
            if (goal == null)
            {
                return HttpNotFound();
            }
            var metrics = metricService.GetMetrics();
            if (goal.Metric != null)
                editGoal.Metrics = metrics.ToSelectListItems(goal.Metric.MetricId);
            else
                editGoal.Metrics = metrics.ToSelectListItems(-1);
            return View(editGoal);
        }

        [HttpPost]
        public ActionResult Edit(GoalFormModel editGoal)
        {
            Goal goalToEdit = Mapper.Map<GoalFormModel, Goal>(editGoal);
            var errors = goalService.CanAddGoal(goalToEdit, updateService);
            ModelState.AddModelErrors(errors);
            if (ModelState.IsValid)
            {
                goalService.EditGoal(goalToEdit);
                return RedirectToAction("Index", new { id = editGoal.GoalId });
            }
            else
            {
                var metrics = metricService.GetMetrics();
                var goalstatus = goalStatusService.GetGoalStatus();
                var goal = goalService.GetGoal(editGoal.GoalId);
                if (goal.Metric != null)
                    editGoal.Metrics = metrics.ToSelectListItems(goal.Metric.MetricId);
                else
                    editGoal.Metrics = metrics.ToSelectListItems(-1);

                return View(editGoal);
            }
        }

        [HttpPost]
        public string GoalStatus(int id, int goalid)
        {
            var goal = goalService.GetGoal(goalid);
            goal.GoalStatusId = id;
            goalService.SaveGoal();
            string msg = goal.GoalStatus.GoalStatusType;
            return msg;
        }

        public ActionResult Delete(int id)
        {
            var goal = goalService.GetGoal(id);
            if (goal == null)
            {
                return HttpNotFound();
            }
            return View(goal);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var goal = goalService.GetGoal(id);
            if (goal == null)
            {
                return HttpNotFound();
            }

            goalService.DeleteGoal(id);
            return RedirectToAction("Index", "Home");
        }

        public PartialViewResult MyGoals()
        {
            string userid = User.Identity.GetUserId();
            var Goals = goalService.GetMyGoals(userid);
            return PartialView("_MyGoalsView", Goals);
        }

        public PartialViewResult GoalsFollowing()
        {
            var followed = supportService.GetUserSupportedGoals(User.Identity.GetUserId(), goalService);
            return PartialView("_FollowedGoals", followed);
        }

        public PartialViewResult DisplayUpdates(int id)
        {
            var Updates = Mapper.Map<IEnumerable<Update>, IEnumerable<UpdateViewModel>>(updateService.GetUpdatesByGoal(id));
            foreach (var item in Updates)
            {
                item.IsSupported = updateSupportService.IsUpdateSupported(item.UpdateId, User.Identity.GetUserId());
            }
            UpdateListViewModel updates = new UpdateListViewModel()
            {

                Updates = Updates,
                Metric = goalService.GetGoal(id).Metric,
                Target = goalService.GetGoal(id).Target,
                // IsSupported =  updateSupportService.IsUpdateSupported(,((SocialGoalUser)(User.Identity)).UserId)
            };
            return PartialView("_UpdateView", updates);
        }

        public ViewResult Supporters(int id)
        {
            var members = supportService.GetSupportersOfGoal(id, userService);
            GoalSupporterViewModel gsvm = new GoalSupporterViewModel() { GoalId = id, Goal = goalService.GetGoal(id), Users = members };
            return View(gsvm);
        }

        [HttpPost]
        public ActionResult SaveUpdate(UpdateFormModel newupdate)
        {
            // Update update = Mapper.Map<UpdateFormModel, Update>(newupdate);
            if (ModelState.IsValid)
            {
                Update update = Mapper.Map<UpdateFormModel, Update>(newupdate);
                update.Goal = goalService.GetGoal(newupdate.GoalId);
                var updateVal = updateService.GetHighestUpdateValue(newupdate.GoalId);
               
                if(updateVal!=null)
                {  
                    if (updateVal.status <= newupdate.status)
                    {
                        updateService.CreateUpdate(update);
                       
                    }
                    else
                    {
                        update.status = -1;
                        ModelState.AddModelError(update.Updatemsg, "cannot enter");
                    }
                }
                else
                {
                    updateService.CreateUpdate(update);
                }


                     var Updates = Mapper.Map<IEnumerable<Update>, IEnumerable<UpdateViewModel>>(updateService.GetUpdatesByGoal(newupdate.GoalId));

HclNextGenSocialGoal/Controllers/HomeController.cs
using HclNextGenSocialGoal.Service;
using HclNextGenSocialGoal.Web.Core.Models;
using HclNextGenSocialGoal.Web.Services;
using HclNextGenSocialGoal.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace HclNextGenSocialGoal.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        IMetricService metricService;
        IFocusService focusService;
        IGoalService goalService;
        ICommentService commentService;
        IUpdateService updateService;
        ISupportService supportService;
        IUserService userService;
        IGroupService groupService;
        IGroupUserService groupUserService;
        IGroupGoalService groupGoalService;
        IGroupUpdateService groupupdateService;
        IGroupCommentService groupcommentService;
        IFollowUserService followUserService;
        ICommentUserService commentUserService;
        IGroupCommentUserService groupCommentUserService;
        IGroupUpdateUserService groupUpdateUserService;
        private readonly CreateNotificationList notificationListCreation = new CreateNotificationList();

        public HomeController(IMetricService metricService, IFocusService focusService, IGoalService goalService, ICommentService commentService, IUpdateService updateService, ISupportService supportService, IUserService userService, IGroupUserService groupUserService, IGroupService groupService, IGroupGoalService groupGoalService, IGroupUpdateService groupupdateService, IGroupCommentService groupcommentService, IFollowUserService followUserService, IGroupUpdateUserService groupUpdateUserService, IGroupCommentUserService groupCommentUserService, ICommentUserService commentUserService)
        {
            this.metricService = metricService;
            this.focusService = focusService;
            this.goalService = goalService;
            this.commentService = commentService;
            this.updateService = updateService;
            this.supportService = supportService;
            this.userService = userService;
            this.groupService = groupService;
            this.groupUserService = groupUserService;
            this.groupGoalService = groupGoalService;
            this.groupupdateService = groupupdateService;
            this.groupcommentService = groupcommentService;
            this.followUserService = followUserService;
            this.groupCommentUserService = groupCommentUserService;
            this.groupUpdateUserService = groupUpdateUserService;
            this.commentUserService = commentUserService;
        }

        /// <summary>
        /// returns all notifications on first load
        /// </summary>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult Index(int page = 0)     
        {
            int noOfRecords = 10;
            HomeViewModel dashboard = new HomeViewModel()
            {
                Notification = GetNotifications(page, noOfRecords),
                Count = GetNotifications(page, noOfRecords).Count()
            };

            if (Request.IsAjaxRequest())
            {
                if (dashboard.Count != 0)
                    return PartialView("Notification", dashboard);
                else
                    return null;
            }
            return View(dashboard);
        }




        public ViewResult About()
        {
            //ViewBag.Message = "Your quintessential app description page.";

            return View();
        }

        public ViewResult Contact()
        {
            //ViewBag.Message = "Your quintessential contact page.";

            return View();
        }







        public PartialViewResult UserNotification(string id)
        {
            HomeViewModel dashboard = new HomeViewModel()
            {
                Notification = GetNotifications(id)
            };
            return PartialView("Notification", dashboard);
        }


        /// <summary>
        /// get notifications paged
        /// </summary>
        /// <param name="?"></param>
        /// <param name="?"></param>
        /// <returns></returns>
        public IEnumerable<NotificationsViewModel> GetNotifications(int page, int noOfRecords)
        {
            var notifications = notificationListCreation.GetNotifications(User.Identity.GetUserId(), goalService, commentService, updateService, supportService, userService, groupService, groupUserService, groupGoalService, groupcommentService, groupupdateService, followUserService, groupCommentUserService, commentUserService, groupUpdateUserService);

            var skipNotifications = noOfRecords * page;
            notifications = notifications.Skip(skipNotifications).Take(noOfRecords);

            return notifications;
        }

        public IEnumerable<NotificationsViewModel> GetNotifications(string userid)
        {

            var notifications = notificationListCreation.GetProfileNotifications(userid, goalService, commentService, updateService, supportService, userService, groupService, groupUserService, groupGoalService, groupcommentService, groupupdateService, commentUserService);
            return notifications;
        }
    }
}

HclNextGenSocialGoal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone:</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email:</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address:</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

HclNextGenSocialGoal/Views/Home/Index.cshtml
@model HclNextGenSocialGoal.Web.ViewModels.HomeViewModel
@{
    ViewBag.Title = "Home";
    Layout = "../Shared/_HomeLayout.cshtml";
}
<script src="/Scripts/bootstrap-tab.js" type="text/javascript"></script>
<div>
    <div class="span6">
        <div id="notification">
            @Html.Partial("Notification",Model)
        </div>

        @if (Model.Count == 10)
        {
             <div  id="morelink"> <a href="#" onclick="loadMore();">More Notifications</a></div>
        }    
    </div>


    <div class="span6">
        <div class="span12 well" style="height:265px;padding-top:5px;">
           <h4>Goals</h4>
           <ul class="nav nav-tabs" id="GoalTab">
              <li class="active"><a href="#MyGoals">My Goals</a></li>
              <li><a href="#FollowedGoals">Followed Goals</a></li>          
            </ul> 
            <div class="tab-content" style="max-height:220px;overflow-y:auto;">
              <div class="tab-pane active" id="MyGoals">@{ Html.RenderAction("MyGoals", "Goal"); }</div>
              <div class="tab-pane" id="FollowedGoals">@{ Html.RenderAction("GoalsFollowing", "Goal"); }</div>    
            </div>
   
        </div>
        <div class="span12 well" style="margin-left:0px;height:265px;padding-top:5px;">
            <h4>Groups</h4>
            <ul class="nav nav-tabs" id="GroupTab">
              <li class="active"><a href="#MyGroups">My Groups</a></li>
              <li><a href="#FollowedGroups">FollowedGroups</a></li>          
            </ul> 
            <div class="tab-content" style="max-height:220px;overflow-y:auto;">
              <div class="tab-pane active" id="MyGroups">@{ Html.RenderAction("GroupsView", "Group"); }</div>
              <div class="tab-pane" id="FollowedGroups">@{ Html.RenderAction("FollowedGroups", "Group"); }</div>    
            </div>
        </div>
     
    </div>

</div>


<style type="text/css">
    .thumbnail
    {
        width: 50px;
        height: 40px;
    }
</style>


<script type="text/javascript">
   
    $(window).scroll(function () {
        if ($(window).scrollTop() == $(document).height() - $(window).height()) {
            loadMore();
        }
    });
    var current = 0;
    function loadMore() {

        if (current > -1) {
            current++;

            $.ajax({
                url: "/Home/Index",
                type: "POST",
                data: { page: current },
                dataType: "html",
                beforeSend: function () {
                    //<img src="/Images/ajax-loader-small.gif"/>
                    $('.msg').remove();
                    $('#morelink').hide();
                    $("#notification").append('<div class="msg alert alert-info" id="loadimage">Loading...</div>');
                },
                success: function (data) {
                    $('.msg').remove();
                    if (data.length != 0) {
                        $("#notification").append(data);
                        $('#morelink').show();
                        var count = data.match(/class="table"/g);
                        if (count.length < 10)
                        { addNoMoreFeeds(); }
                    }
                    else {
                        addNoMoreFeeds();
                    }
                }
            });

        }
        function addNoMoreFeeds() {
            $('#morelink').hide();
            current = -1;
            $("#notification").append('<div class="msg alert alert-info" id="alertmsg"> No more feeds </div>');

        }
    }

    $('#GroupTab a').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    });
    $('#GoalTab a').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    });


   
</script>

HclNextGenSocialGoal/Views/Home/Notification.cshtml
@using HclNextGenSocialGoal.Web.Core.Extensions
@model HclNextGenSocialGoal.Web.ViewModels.HomeViewModel
@if (Model.Notification.Count() == 0)
{ 
    <p style="padding:30px;margin-top:5px;line-height:25px;text-align:justify;">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@*Social Goal is a social networking platform for goals. 
        Users can create their accounts in Social Goal and start setting their goals. The goals can be private or public.
        A public goal is visible to all other users in the system. Users can follow other
        users or goals. User can put updates and status on the created goals and the followers
        can comment on it. Also a graphical representation of goal progress is available.
   It is also possible to create group goals where the goals and updates are visible
        only for the group members. Users can invite other Social Goal users to follow a
        goal or to join a group. Invitations can also send through emails. Users receive
        updates of followed users and goals. Goals, users and groups can be searched from
        a search bar on the header.*@No feeds available.  Connect with people.</p>

}
else
{ 
foreach (var item in Model.Notification)
{
    if (item.NotificationType == 0)
    {

    <table class="table">
        <tr class="span12">
            <td class="span2">
                <a href="@Url.Action("UserProfile", "Account", new { id = item.UserId }, null)"  style="float:left;">
                    @Html.User().Avatar(item.ProfilePicUrl)
                </a>
            </td>
            <td class="span10">
                <div>
                    @Html.ActionLink(item.UserName, "UserProfile", "Account", new { id = item.UserId }, null)
                    Created @Html.ActionLink(item.GoalName/*.LimitLength(15)*/, "Index", "Goal", new { id = item.GoalId }, null)
                </div>
                <small style="float: left; color: darkGray; margin-top: 5px;">@item.NotificationDate
                </small>
            </td>
        </tr>
    </table>

    }

    if (item.NotificationType == 1)
    { 

    <div>
        <table class="table">
            <tr class="span12">
                <td class="span2">
                    <a href="@Url.Action("UserProfile", "Account", new { id = item.UserId }, null)"  style="float:left;">
                        @Html.User().Avatar(item.ProfilePicUrl)
                    </a>
                </td>
                <td class="span10">
                    <div>
                        @Html.ActionLink(item.UserName, "UserProfile", "Account", new { id = item.UserId }, null)
                        Updated @Html.ActionLink(item.Updatemsg/*.LimitLength(15)*/, "Index", "Goal", new { id = item.GoalId }, null)
                        On Goal
                        @Html.ActionLink(item.GoalName/*.LimitLength(15)*/, "Index", "Goal", new { id = item.GoalId }, null)
                        <br />
                    </div>
                    <small style="float: left; color: darkGray; margin-top: 5px;">@item.NotificationDate
                    </small>
                </td>
            </tr>
        </table>
    </div>

	
    }
    if (item.NotificationType == 2)
    {
    <table class="table">
        <tr class="span12">
            <td class="span2">
                <a href="@Url.Action("UserProfile", "Account", new { id = item.UserId }, null)" style="float:left;">
                    @Html.User().Avatar(item.ProfilePicUrl)
                </a>
            </td>
            <td class="span10">
                <div>
                    @Html.ActionLink(item.UserName, "UserProfile", "Account", new { id = item.UserId }, null)
                    @*Commented "@item.CommentText.LimitLength(15)" on Update @Html.ActionLink(item.Updatemsg.LimitLength(15), "Index", "Goal", new { id = item.GoalId }, null)*@
                    Commented "@item.CommentText" on Update @Html.ActionLink(item.Updatemsg, "Index", "Goal", new { id = item.GoalId }, null)
                    of Goal @Html.ActionLink(item.GoalName/*.LimitLength(15)*/, "Index", "Goal", new { id = item.GoalId }, null)
                </div>
                <small style="float: left; color: darkGray; margin-top: 5px;">@item.NotificationDate
                </small>
            </td>
        </tr>
    </table>
    }
    if (item.NotificationType == 3)
    { 

    <table class="table">
        <tr class="span12">
            <td class="span2">
                <a href="@Url.Action("UserProfile", "Account", new { id = item.UserId }, null)" style="float:left;">
                    @Html.User().Avatar(item.ProfilePicUrl)
                </a>
            </td>
            <td class="span10">
                <div>
                    @Html.ActionLink(item.UserName, "UserProfile", "Account", new { id = item.UserId }, null)
                    Created Goal @Html.ActionLink(item.GroupGoalName/*.LimitLength(15)*/, "GroupGoal", "Group", new { id = item.GroupGoalId }, null)
                    for the Group @Html.ActionLink(item.GroupName/*.LimitLength(15)*/, "Index", "Group", new { id = item.GroupId }, null)
                </div>
                <small style="float: left; color: darkGray; margin-top: 5px;">@item.NotificationDate
                </small>
            </td>
        </tr>
    </table>

    }
    if (item.NotificationType == 5)
    {

    <table class="table">
        <tr class="span12">
            <td class="span2">
                <a href="@Url.Action("UserProfile", "Account", new { id = item.UserId }, null)"  style="float:left;">
                    @Html.User().Avatar(item.ProfilePicUrl)
                </a>
            </td>
            <td class="span10">
                <div>
                    @Html.ActionLink(item.UserName, "UserProfile", "Account", new { id = item.UserId }, null)
                    Joined Group @Html.ActionLink(item.GroupName/*.LimitLength(15)*/, "Index", "Group", new { id = item.GroupId }, null)
                </div>
                <small style="float: left; color: darkGray; margin-top: 5px;">@item.NotificationDate
                </small>
            </td>
        </tr>
    </table>
    }
    if (item.NotificationType == 4)
    {
    <table class="table">
        <tr class="span12">
            <td class="span2">
                <a href="@Url.Action("UserProfile", "Account", new { id = item.UserId }, null)"  style="float:left;">
                    @Html.User().Avatar(item.ProfilePicUrl)
                </a>
            </td>
            <td class="span10">
                <div>
                    @Html.ActionLink(item.UserName, "UserProfile", "Account", new { id = item.UserId }, null)
                    is Following the Goal @Html.ActionLink(item.GoalName/*.LimitLength(15)*/, "Index", "Goal", new { id = item.GoalId }, null)
                </div>
                <small style="float: left; color: darkGray; margin-top: 5px;">@item.NotificationDate
                </small>
            </td>
        </tr>
    </table>
        
    }
    if (item.NotificationType == 6)
    {

    <table class="table">
        <tr class="span12">
            <td class="span2">
                <a href="@Url.Action("UserProfile", "Account", new { id = item.UserId }, null)"  style="float:left;">
                    @Html.User().Avatar(item.ProfilePicUrl)
                </a>
            </td>
            <td class="span10">
                <div>
                    @Html.ActionLink(item.UserName, "UserProfile", "Account", new { id = item.UserId }, null)
                    Updated @Html.ActionLink(item.GroupUpdatemsg/*.LimitLength(15)*/, "GroupGoal", "Group", new { id = item.GroupGoalId }, null)
                    on the Goal @Html.ActionLink(item.GroupGoalName/*.LimitLength(15)*/, "GroupGoal", "Group", new { id = item.GroupGoalId }, null)
                    for the Group @Html.ActionLink(item.GroupName/*.LimitLength(15)*/, "Index", "Group", new { id = item.GroupId }, null)
                </div>
                <small style="float: left; color: darkGray; margin-top: 5px;">@item.NotificationDate
                </small>
            </td>
        </tr>
    </table>

    }



    if (item.NotificationType == 7)
    {

    <table class="table">
        <tr class="span12">
            <td class="span2">
                <a href="@Url.Action("UserProfile", "Account", new { id = item.UserId }, null)" style="float:left;">
                    @Html.User().Avatar(item.ProfilePicUrl)
                </a>
            </td>
            <td class="span10">
                <div>
                    @Html.ActionLink(item.UserName, "UserProfile", "Account", new { id = item.UserId }, null)
                    @*Commented "@item.GroupCommentText.LimitLength(15)" on Update @Html.ActionLink(item.GroupUpdatemsg.LimitLength(15), "GroupGoal", "Group", new { id = item.GroupGoalId }, null)*@
                    Commented "@item.GroupCommentText" on Update @Html.ActionLink(item.GroupUpdatemsg, "GroupGoal", "Group", new { id = item.GroupGoalId }, null)
                    of the Goal @Html.ActionLink(item.GroupGoalName/*.LimitLength(15)*/, "GroupGoal", "Group", new { id = item.GroupGoalId }, null)
                    for the Group @Html.ActionLink(item.GroupName/*.LimitLength(15)*/, "Index", "Group", new { id = item.GroupId }, null)
                </div>
                <small style="float: left; color: darkGray; margin-top: 5px;">@item.NotificationDate
                </small>
            </td>
        </tr>
    </table>

    }

    if (item.NotificationType == 8)
    { 

    <table class="table">
        <tr class="span12">
            <td class="span2">
                <a href="@Url.Action("UserProfile", "Account", new { id = item.FromUserId }, null)"  style="float:left;">
                    @Html.User().Avatar(item.ProfilePicUrl)
                </a>
            </td>
            <td class="span10">
                <div>
                    @Html.ActionLink(item.FromUser.UserName, "UserProfile", "Account", new { id = item.FromUserId }, null)
                    is Following @Html.ActionLink(item.ToUser.UserName, "UserProfile", "Account", new { id = item.ToUserId }, null)
                </div>
                <small style="float: left; color: darkGray; margin-top: 5px;">@item.NotificationDate
                </small>
            </td>
        </tr>
    </table>

    }
}
}